version: '3.8'

services:
  nginx:
    image: nginx
    container_name: ingressysite
    ports:
      - "3012:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - zoraxynet

  php:
    build: .
    container_name: ingressyphp
    volumes:
      - ./html:/var/www/html
    networks:
      - zoraxynet

networks:
  zoraxynet:
    driver: bridge
    external: true

